services:
  mysql:
    image: mysql:8.3.0
    container_name: shared-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - micro_kube_net

  mongodb:
    image: mongo:7.0.5
    container_name: shared-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongodb:/data/db
    networks:
      - micro_kube_net

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    networks:
      - micro_kube_net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    networks:
      - micro_kube_net

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "8083:8080"
    depends_on:
      - mysql
    networks:
      - micro_kube_net

networks:
  micro_kube_net:
    driver: bridge
